site_name: MedDocs

pages:
  - Home: 'index.md'
  - MedLearn Pilot Student Guide:
    - Dashboard: 'student-dashboard.md'
    - Courses: 'student-courses.md'
    - Grades: 'student-grades.md'
    - Assignments: 'student-assignments.md'
    - Assessments & Evaluations: 'student-ae.md'
    - Absences: 'student-absences.md'
    - Profile: 'student-profile.md'
  - MedLearn Pilot Coordinator Guide: 'coordinator-pilot.md'

theme: readthedocs
