site_name: MedDocs

pages:
  - Home: 'index.md'
  - MedLearn Pilot Student Guide:
    - 1. Dashboard: 'student-dashboard.md'
    - 2. Courses: 'student-courses.md'
    - 3. Grades: 'student-grades.md'
    - 4. Assignments: 'student-assignments.md'
    - 5. Assessments & Evaluations: 'student-ae.md'
    - 6. Absences: 'student-absences.md'
    - 7. Profile: 'student-profile.md'

  - MedLearn Pilot Coordinator Guide:
    - 1. Dashboard: 'coordinator-dashboard.md'
    - 2. Courses: 'Coordinator-Courses.md'
    - 2.1. Edit Courses: 'Coordinator-EditCourses.md'
    - 2.1.1. Course Setup: 'Coordinator-CourseSetup.md'
    - 2.1.2. Course Content: 'Coordinator-CourseContent.md'
    - 2.1.3. View Enrollment: 'Coordinator-ViewEnrollment.md'
    - 2.1.4. Course Groups: 'Coordinator-CourseGroups.md'
    - 3. Events: 'coordinator-events.md'
    - 3.1. Select and Search Learning Events: 'Coordinator-SelectSearchLearningEvents.md'
    - 3.2. Setting Up Learning Events: 'Coordinator-LearningEventSetup.md'
    - 3.3. Adding Content to Learning Events: 'Coordinator-LearningEventAddContent.md'
    - 3.4. Faculty Notes: 'Coordinator-FacultyNotes.md'
    - 3.5. Taking Attendance: 'Coordinator-TakeAttendance.md'
    - 3.6. Event History & Statistics: 'Coordinator-EventHistoryStatistics.md'
    - 3.7. Delete Learning Events: 'Coordinator-DeleteLearningEvents.md'
    - 3.8. Create Learning Events: 'Coordinator-CreateLearningEvents.md'
    - 4. ILMs: 'Coordinator-ILMs.md'
    - 5. Messages AKA Notices: 'Coordinator-Messages.md'
    - 6. Gradebook: 'Coordinator-Gradebook.md'
    - 6.1. Set Passing Scores for Each Competency: 'Coordinator-UpdatePassingScore.md'
    - 6.2. Add and Edit Assessments: 'coordinator-addeditassessments.md'
    - 6.3. Manually Enter Assessment Scores: 'Coordinator-ManualEntryAssessmentScores.md'
    - 6.4. Import Assessment Scores: 'Coordinator-ImportAssessmentScores.md'
    - 6.5. Enter Grade Adjustments: 'Coordinator-EnterGradeAdjustments.md'
    - 6.6. Grade Spreadsheet: 'Coordinator-GradeSpreadsheet.md'
    - 6.7. Final and Retake Grades: 'Coordinator-FinalAndRetakeGrades.md'
    - 7. Manage Absences: 'Coordinator-ManageAbsences.md'
    - 7.1. Enter Absences: 'Coordinator-EnterAbsences.md'
    - 7.2. Approve or Deny Absence Requests: 'coordinator-ApproveDenyPassDays.md'
    - 7.3. Delete Absence Requests: 'Coordinator-DeleteAbsenceRequests.md'

theme: readthedocs
