site_name: MedDocs for Students

nav:
- Welcome: "index.md"
- MedPortal: "01_MedPortal.md"
- MedLearn: "02_MedLearn.md"
- MedLearn / Dashboard: "03_MedLearn_Dashboard.md"
- MedLearn / Curriculum: "04_MedLearn_Curriculum.md"
- MedLearn / Courses: "05_MedLearn_Courses.md"
- MedLearn / Learning Events: "06_MedLearn_Events.md"
- MedLearn / Course Groups: "12_MedLearn_Groups.md"
- MedLearn / Grades: "10_MedLearn_Grades.md"
- MedLearn / Assignments: "11_MedLearn_Assignments.md"
- MedLearn / ILM: "06_MedLearn_ILM.md"
- MedLearn / Assessment & Evaluation (Surveys): "08_MedLearn_AE.md"
- MedLearn / Absence Requests: "13_MedLearn_Absences.md"
- MedLearn / Duty Hours: "15_MedLearn_DutyHours.md"
- MedLearn / Logbook: "16_MedLearn_Logbook.md"
- MedLearn / Alternative Experience: "17_MedLearn_AltExp.md"
- MedLearn / MSPE Noteworthy Characteristics: "14_MedLearn_MSPE.md"
- MedLearn / Profile: "09_MedLearn_Profile.md"
- MedLearn / People Search: "07_MedLearn_People.md"
- MedLearn / Societies: "18_MedLearn_Societies.md"
- MedLearn & iAnnotate: "iannotate.md"
- MedLearn & Notability: "notability.md"
- MedLearn & OneNote: "onenote.md"
- MedReports: "MedReports.md"
- OASIS / Third Year Lottery: "Oasis_lottery.md"

theme:
    name: readthedocs
    custom_dir: custom_theme/