site_name: MedDocs for Students

nav:
- Welcome: "index.md"
- MedPortal: "MedPortal.md"
- MedLearn: "MedLearn.md"
- MedLearn / Dashboard: "MedLearn_Dashboard.md"
- MedLearn / Curriculum: "MedLearn_Curriculum.md"
- MedLearn / Courses: "MedLearn_Courses.md"
- MedLearn / Learning Events: "MedLearn_Events.md"
- MedLearn / Course Groups: "MedLearn_Groups.md"
- MedLearn / Grades: "MedLearn_Grades.md"
- MedLearn / Assignments: "MedLearn_Assignments.md"
- MedLearn / ILM: "MedLearn_ILM.md"
- MedLearn / Assessment & Evaluation (Surveys): "MedLearn_AssessmentEvaluation.md"
- MedLearn / Absence Requests: "MedLearn_Absences.md"
- MedLearn / Duty Hours: "MedLearn_DutyHours.md"
- MedLearn / Logbook: "MedLearn_Logbook.md"
- MedLearn / Alternative Experience: "MedLearn_AltExp.md"
- MedLearn / MSPE Noteworthy Characteristics: "MedLearn_MSPE.md"
- MedLearn / Profile: "MedLearn_Profile.md"
- MedLearn / People Search: "MedLearn_People.md"
- MedLearn / Societies: "MedLearn_Societies.md"
- MedLearn & iAnnotate: "iannotate.md"
- MedLearn & Notability: "notability.md"
- MedLearn & OneNote: "onenote.md"
- MedReports: "MedReports.md"
- OASIS / Third Year Lottery: "Oasis_lottery.md"

theme:
    name: readthedocs
    custom_dir: custom_theme/